server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: user
    password: 12345

    platform: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc.lob.non_contextual_creation: true
